<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{{ ucfirst(str_replace('_', ' ', $type)) }} Export</title>
<style>
body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
h1 { color: #6366f1; font-size: 18px; margin-bottom: 20px; }
table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
th { background: #6366f1; color: white; padding: 8px 10px; text-align: left; font-size: 11px; }
td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
tr:nth-child(even) td { background: #f8fafc; }
.footer { text-align: center; color: #999; font-size: 10px; margin-top: 30px; }
</style>
</head>
<body>
<h1>My {{ ucfirst(str_replace('_', ' ', $type)) }} - {{ date('F d, Y') }}</h1>
<table>
<thead>
<tr>
    <th>#</th>
    <th>Question / Front</th>
    <th>Answer / Back</th>
    <th>Subject</th>
</tr>
</thead>
<tbody>
@forelse($questions as $q)
<tr>
    <td>{{ $loop->iteration }}</td>
    <td>{{ strip_tags($q->question ?? $q->statement ?? $q->sentence_with_blanks ?? $q->front ?? ($type === 'matching' ? 'Matching Exercise' : '')) }}</td>
    <td>
        @switch($type)
            @case('mcqs')
                {{ $q->correct_answer }} @if($q->explanation)({{ $q->explanation }})@endif
                @break
            @case('true_false')
                {{ $q->correct_answer ? 'True' : 'False' }}
                @break
            @case('short_answers')
                {{ strip_tags($q->expected_answer ?? '') }}
                @break
            @case('fill_blanks')
                {{ is_array($q->answers) ? implode(', ', $q->answers) : $q->answers }}
                @break
            @case('matching')
                Left: {{ is_array($q->left_items) ? implode('; ', $q->left_items) : $q->left_items }}
                Right: {{ is_array($q->right_items) ? implode('; ', $q->right_items) : $q->right_items }}
                @break
            @case('flashcards')
                {{ strip_tags($q->back ?? '') }}
                @break
        @endswitch
    </td>
    <td>{{ $q->subject?->name ?? 'General' }}</td>
</tr>
@empty
<tr><td colspan="4" style="text-align:center;color:#999;">No questions found.</td></tr>
@endforelse
</tbody>
</table>
<div class="footer">Generated by {{ config('app.name') }} on {{ date('Y-m-d H:i') }}</div>
</body>
</html>
